apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mono-deployment
  labels:
    app: mono-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mono-app
  template:
    metadata:
      labels:
        app: mono-app
    spec:
      containers:
      - name: hello-mono-container
        image: gcr.io/nzzi-test-project/hello-repo:latest
        ports:
        - containerPort: 8080