apiVersion: apps/v1
kind: Deployment
metadata:
  name: mono-app
  labels:
    app: mono-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mono-app
  template:
    metadata:
      labels:
        app: mono-app
    spec:
      containers:
      - name: hello-container
        image: gcr.io/nzzi-test-project/hello-repo:latest
        ports:
        - containerPort: 8080