apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mono-app
  labels:
    app: hello-mono-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-mono-app
  template:
    metadata:
      labels:
        app: hello-mono-app
    spec:
      containers:
      - name: hello-mono-app
        image: gcr.io/nzzi-test-project/hello-repo:latest
        ports:
        - containerPort: 8080