apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmg-mono-app
  labels:
    app: pmg-mono-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pmg-mono-app
  template:
    metadata:
      labels:
        app: pmg-mono-app
    spec:
      containers:
      - name: pmg-mono-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080